version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: dep-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build: .
    container_name: dep-backend
    restart: always
    ports:
      - 5001:5001
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=mongodb://admin:password@mongodb:27017/digital-europe?authSource=admin
      - JWT_SECRET=jotain_salaista_muutettava_tuotannossa
      - OPENAI_API_KEY=sinun_openai_api_avain
      - GEMINI_API_KEY=sinun_gemini_api_avain
      - OPENROUTER_API_KEY=sinun_openrouter_api_avain
      - DEFAULT_AI_PROVIDER=openai
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: